
title: Jason Nerida Resume
url: 'http://webjeda.com'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #
# style: styles-2
# style: styles-3
# style: styles-4
# style: styles-5
style: styles-6




#Profile information
name: Jason Nerida
tagline: Fron End Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
resume: jason_nerida_resume_2016.pdf

#sidebar links
email: hello@jasonnerida.com
phone: 206 293 3745
website: blog.webjeda.com #do not add http://
linkedin: jasonnerida
github: neridaj
twitter: '@neridaj'
